version: '3'

tasks:
  migrate-step:
    desc: Apply DB migrations for StepManagment
    cmds:
      - dotnet ef database update ${migrationName:-} --project StepManagmentService/src/StepManagment.infrastructure --startup-project StepManagmentService/src/StepManagment.api

  migrate-user:
    desc: Apply DB migrations for UserManagment
    cmds:
      - dotnet ef database update ${migrationName:-} --project UserManagmentService/src/UserManagment.infrastructure --startup-project UserManagmentService/src/UserManagment.api

  migrate-all:
    desc: Apply DB migrations for all services
    deps:
      - migrate-step
      - migrate-user

  add-step-migration:
    desc: Create migration for StepManagment
    cmds:
      - dotnet ef migrations add ${migrationName:-init} --project StepManagmentService/src/StepManagment.infrastructure --startup-project StepManagmentService/src/StepManagment.api

  add-user-migration:
    desc: Create migration for UserManagment
    cmds:
      - dotnet ef migrations add ${migrationName:-init} --project UserManagmentService/src/UserManagment.infrastructure --startup-project UserManagmentService/src/UserManagment.api

  run-step:
    desc: "Build and run Journify StepManagmentService container"
    cmds:
      - docker build -t kuber/journify-step:latest -f StepManagmentService/Dockerfile .
      - docker run -d -p 8080:8080 --name journify_step_test kuber/journify-step:latest

  run-user:
    desc: "Build and run Journify UserManagmentService container"
    cmds:
      - docker build -t kuber/journify-user:latest -f UserManagmentService/Dockerfile .
      - docker run -d -p 8081:8081 --name journify_user_test kuber/journify-user:latest
  run-api:
    desc: "Build and run Journify API Gateway container"
    cmds:
      - docker build -t kuber/journify-apigateway:latest -f OcelotApiGateway/Dockerfile .
      - docker run -d -p 8082:8082 --name journify_api_test kuber/journify-apigateway:latest